from time import time

from utility.printable import Printable
from utility.hash_util import hash_block

# Block class represents a single block of our blockchain
    # index: The index of this block
    # previous_hash: The hash of the previous block in the blockchain
    # timestamp: The timestamp of the block (automatically generated by default)
    # transactions: A list of transaction which are included in the block
    # proof: The proof of work number that yielded this block
class Block(Printable):
    def __init__(self, index, previous_hash, transactions, proof, mined_by, timestamp=time(), hashh='',):
        self.index = index
        self.previous_hash = previous_hash
        self.timestamp = timestamp
        self.transactions = transactions
        self.proof = proof
        self.mined_by = mined_by
        self.hash = hashh


